server:
  port: 8081
  
spring:  jpa:    database: h2    hibernate:      ddl-auto: update  datasource:    url: jdbc:h2:~/test-springboot
    username: test-springboot
    password: P@ssw0rd